### ISSUE TITLE
Modification for VMAT Legs

### ISSUE THREAD

**Issue by crcrewso** [esimiele/VMAT-TBI#11]
We would like to see a new option where the legs could also be set to VMAT when needed. This is a change as part of bringing this tool clinical and we will be returning the change back upstream. I'd be happy to discuss any impacts here!

Line reference for sanity
https://github.com/esimiele/VMAT-TBI/blob/1f20b17b8d12595836d9dd9cf77297c619d70b7b/ESAPI/Projects/VMATTBIautoPlan/placeBeams.cs#L61

**Comment by esimiele** [comment]
Will make this change in the near future (next week or so if you don't beat me to it haha!), but will need your help testing it as we don't do TMI/TMLI at Stanford or Rutgers using VMAT.

**Comment by esimiele** [comment]
This feature is now (partially) available in the latest version of the code on the beta branch. You can now specify in the configuration file (plug-in portion) to set all fields to use the VMAT technique. No modification was needed for the executable. 
I've only tested it once and it worked fine. However, it will likely require some fine-tuning for sure. Also note, this feature is not complete as you won't be able to treat with the created plan. The script optimizes all of the VMAT fields in one plan with the patient in the HFS position. Code will need to be added to the plan preparation section to copy the original plan, remove all fields superior to the matchline, take all the fields inferior to the matchline and reverse the field orientations and control points. You will need to manually change the patient orientation in the new plan to FFS, recalculate the dose, and create a plan sum. All of these things will be addressed when I get a chance. Let me know what you think!

**Comment by crcrewso** [comment]
> The script optimizes all of the VMAT fields in one plan with the patient in the HFS position. Code will need to be added to the plan preparation section to copy the original plan, remove all fields superior to the matchline, take all the fields inferior to the matchline and reverse the field orientations and control points.

Thank you, that's the next step I wanted to discuss. We currently have a matlab script doing that control point manipulation. I was debating writing an eclipse script or adding to yours to reorient the leg plans.

**Comment by esimiele** [comment]
Cool! No worries, The logic should be pretty simple. It's the ESAPI syntax that will be a pain in the butt to figure out. Could you send the snippet of your matlab code that reverses the control points (via DM)? Will be a nice double check of my logic

**Comment by crcrewso** [comment]
I talked with the author, and he's okay with me posting it here. We've gone with 175 and 185 for collimator angles which gives us 355, and 5 for the clinical plan. 

I realized I had never shared my solution, though yours looks more readable then mine. Our clinical practice currently is to use the same energy for the legs as for the body, I'm not sure what the generally accepted practice will be going forward. 

```MATLAB
Info = dicominfo(file);     %Dicom info
RPmodified = Info;          %New plan file
FN = fieldnames(Info.BeamSequence);     %Number of beams
BeamNumber = length(FN);

for i=1:BeamNumber          %Loop through beams
    
    CPcount = Info.BeamSequence.(FN{i}).NumberOfControlPoints;      %Number of control points
    CPList = fieldnames(Info.BeamSequence.(FN{i}).ControlPointSequence);    %Control points
    ControlPoints = Info.BeamSequence.(FN{i}).ControlPointSequence;

    for j=1:CPcount     %Loop through control points
        
        if j==1         %First control point set col angle
           Col = ControlPoints.(CPList{j}).BeamLimitingDeviceAngle;  %Angle 
           if Col > 180
               Col = Col-180;   
           else 
              Col = Col+180;   %Flip 180 degrees
           end
           RPmodified.BeamSequence.(FN{i}).ControlPointSequence.(CPList{j}).BeamLimitingDeviceAngle = Col;
        end


        Dir = ControlPoints.(CPList{j}).GantryRotationDirection;     %Gantry rotation direction
        if strcmp(Dir,'CW')     %If CW set to CC
            RPmodified.BeamSequence.(FN{i}).ControlPointSequence.(CPList{j}).GantryRotationDirection = 'CC';
        elseif strcmp(Dir,'CC')     %If CC set to CW
            RPmodified.BeamSequence.(FN{i}).ControlPointSequence.(CPList{j}).GantryRotationDirection = 'CW';
        elseif strcmp(Dir,'NONE')   %Last control point has direction set as 'NONE'
            'Done'
            i   %Do nothing
        else
            error('Undefined Gantry')
        end
       
        swapAngle = ControlPoints.(CPList{CPcount-j+1}).GantryAngle;  %Swap angle with opposite 1-178 2-177 3-176 etc...
        RPmodified.BeamSequence.(FN{i}).ControlPointSequence.(CPList{j}).GantryAngle = swapAngle;
 
    end
end
```

**Comment by esimiele** [comment]
This feature and the reversal of the control points will be implemented in a future release of:
https://github.com/esimiele/VMAT-TBI-CSI

as we expand into VMAT TMI/TMLI
