### ISSUE TITLE
Spinning Manny Notice

### ISSUE THREAD

**Issue by crcrewso** [esimiele/VMAT-TBI#12]
There should be a configuration option to turn off this notice, since not every clinic will have a spinning manny or similar. 

https://github.com/esimiele/VMAT-TBI/blob/1f20b17b8d12595836d9dd9cf77297c619d70b7b/ESAPI_MT/VMATTBI_optLoopMT/VMATTBI_optLoopMT/optimizationLoop.cs#L244

I'll probably push a PR request on this one in the near future.

**Comment by esimiele** [comment]
Good catch! Especially since there is no commercial option in North America yet. I'll make this change in the next week or so and will follow up

**Comment by esimiele** [comment]
Should be fixed in the latest version of the code on the beta branch (v1.5 I believe). You can now specify in the configuration file if a check for the spinning manny couch should be performed
