### ISSUE TITLE
Patient body cropping behaviour

### ISSUE THREAD

**Issue by crcrewso** [esimiele/VMAT-TBI#13]
There should be a configuration option to turn off this behaviour for clinics that have differing clinical practices

https://github.com/esimiele/VMAT-TBI/blob/1f20b17b8d12595836d9dd9cf77297c619d70b7b/ESAPI/Projects/VMATTBIautoPlan/generateTS.cs#L403

I'll probably push a PR request on this one in the near future.

**Comment by esimiele** [comment]
Agreed. I will probably roll things update into the all VMAT request as the two require similar modifications.

**Comment by esimiele** [comment]
This has been partially addressed in the latest version of the code on the beta branch. Specifically, the cropping of the targets is automatically disabled when all fields are requested to be VMAT.

**Comment by esimiele** [comment]
Assuming this issue is resolved. Closing
