### ISSUE TITLE
Default course name

### ISSUE THREAD

**Issue by crcrewso** [esimiele/VMAT-TBI#14]
Thinking about broader use cases, it would be nice if the course name generated could be set in the config file. 

Ideally one could select the course in the application from any course in the patient, but I don't see that as an easy feature and I'd rather have this as a happy medium.

**Comment by esimiele** [comment]
A new code version has been pushed to the beta branch. You can now specify the default course Id in the configuration file. Might change it in the future to select an existing course from the patient as you suggested, but this should work for now.

**Comment by crcrewso** [comment]
That looks great! Thank you. 
I notice there is a lot of string comparison and not much of it is case safe. Would you consider switching to a library for the config file? Something like TOML or YAML?
