### ISSUE TITLE
Eclipse version incorrect

### ISSUE THREAD

**Issue by ysgeng** [esimiele/VMAT-TBI#15]
I'm experiencing an issue with the stand alone scripts. When I start it in Visual Studio, the following message pops up:

VMS.TPS.Common.Model.TpsNetInitializationException: The application Eclipse Client is running an incorrect version (16.1.3). The system is configured to run version 16.1.4 of this application family. It is not possible to start older versions of the application. Please contact Varian Customer Support to have this issue resolved. The application will now exit.

   at VMS.TPS.Common.Model.ApplicationInitGuard.End()
   at VMS.TPS.Common.Model.ApplicationInitGuard.InitializeApplicationImpl(Delegate initDelegate, Object[] args)
   at VMS.TPS.Common.Model.ApplicationNonAppFrame.Initialize(IStartupParameters startupParameters, IApplicationContextInfo applicationContextInfo)
   at VMS.TPS.Common.Model.API.Application.CreateApplicationCommon(String scriptName, Func`2 createExecutionGuardFunc)

Any suggestion will be appreciated.

Thank you.

**Comment by esimiele** [comment]
Interesting, I have not seen this error before. I'm guessing your Eclipse version (and hence ESAPI version) are newer than the version the scripts were built in (16.1.3). Do you also get this error when running the plugin script?
A potential fix, open the standalone script solution in visual studio-->expand the references in the project in the solution explorer-->delete the two VMS.TPS references->right click on References->Add Reference->Add the VMS.TPS references installed LOCALLY on your computer (not the dlls provided with the code). These typically reside somewhere on the C: drive (something like C:\Program Files (x86)\Varian) The VMS.TPS dll files installed locally on your computer should be specific to your version of Aria/Eclipse. 

Give the above solution a fix and let me know if it works.

![References](https://user-images.githubusercontent.com/53239553/194715163-cd16846a-e6b1-4e46-976e-f86a0e437dd5.png)

**Comment by ysgeng** [comment]
Thank you very much for replying.
The plug in script works fine, this error only shows up in the stand alone script. Replacing the local dll files is the first thing I tried, but it doesn't help.

Update: I found the VMS.TPS.Common.Model.Types.dll is at version 16.1.4, but I cannot find the same version of VMS.TPS.Common.Model.API.dll. That must be the problem.

**Comment by esimiele** [comment]
No problem. Interesting, does visual studio throw this error with any stand-alone application? 
Ahh that would do it. You'll need to ask Varian to provide the appropriate dll files for your specific version of Eclipse.
Let me know if that fixes the issue.
Update: I'll close this issue for now, but if it turns out to be a problem with the code, let me know and I'll reopen the issue

**Comment by ysgeng** [comment]
Update: I reinstalled Varian_Eclipse_Scripting 16.1 MR1, the two dll files now match to our current Eclipse version. Everything is working without any error.

Thank you very much.

**Comment by esimiele** [comment]
Yay!! No Problem!
