### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by ysgeng** [esimiele/VMAT-TBI#18]
Hello,
I was testing the optimazation loop script in demo mode, and I got an error as follows. It complains the dvh was null.
I wonder if someone may have some suggestions on this.
![image](https://user-images.githubusercontent.com/38668449/200389249-71d7dfe0-b4d6-4d79-81e7-dce411460059.png)
Thank you very much.

**Comment by esimiele** [comment]
Hey ysgeng,

Yes, others have observed this before and it's my fault for not clearly explaining how to use demo mode. You are likely getting this because you haven't calculated dose in the created VMAT TBI plan (which will result in a null result when trying to evaluate the DVH in the code). To fix this, you can open the created VMAT TBI plan in Eclipse and simply hit the calculate dose button (open fields will do with no optimization). Once dose has been calculated, hit save. Try and rerun the executable now in demo mode and it should work.

Let me know if you still have issues.
Thanks!

**Comment by ysgeng** [comment]
Thanks a lot for replying.

After doing so, I think I have 2 questions now.

1. When the demo mode is true, it returns me an error saying cannot access the cal model.
 ![image](https://user-images.githubusercontent.com/38668449/201184551-7792e450-2977-4e90-9cfd-fb612c7fa6cb.png)
![image](https://user-images.githubusercontent.com/38668449/201184620-61c1a052-a61e-4bdc-9a54-192a1235a61a.png)

2. When the domo mode is false, it throws me another error as follows, but I'm not sure what change should I make in Eclipse.
![image](https://user-images.githubusercontent.com/38668449/201182176-750b99e1-536c-43b2-9088-6805e38d1f52.png)
![image](https://user-images.githubusercontent.com/38668449/201182330-99104095-2b7f-4bdf-8e62-e83fb39a3a49.png)

I really appreciate your help and your time.

**Comment by esimiele** [comment]
Hmmmm interesting. I haven't run into those errors before. Your clinic is running v16, correct? Do you have a plan that references the VMAT TBI structure set with calculated dose? Was this plan created using the script or by you? Or was the dose imported? My guess would be that it is complaining about a plan that references the structure set you are trying to use that has dose imported (in which case, some of the calculation parameters may not have been set, such as calculation model). The DCF error I have never run into before. I would post that error on the esapi reddit page (https://www.reddit.com/r/esapi/) and see if any of the other scripting gurus have seen that error before. My guess is there is some configuration issue preventing esapi from accessing the DCF. Are you able to optimize the plan in Eclipse? If so, are you able to run other auto planning scripts? If so, then it is an issue specific to the VMAT TBI scripts. If not, then it is likely some problem in the configuration of Eclipse/ESAPI. Sorry I can't be of more help, but I would be very interested in what you find.

**Comment by esimiele** [comment]
Closing this issue as resolved

**Comment by ysgeng** [comment]
I'm circling back in case anyone else ran into the same situation.

It turns out it's our local IT blocking the access of all exe files. We ended up with putting everything directly on the Citrix server and get things going. 

Thank you.

**Comment by esimiele** [comment]
Thanks for following up on this! I'm glad you figured it out and were able to work around the issue. Have fun!
