### ISSUE TITLE
Wrong Course found

### ISSUE THREAD

**Issue by crcrewso** [esimiele/VMAT-TBI#24]
In the Beta branch with the modification allowing for any course, if a user has two courses created from the script the wrong plan from the wrong course may be chosen by the loop for continued optimization

suggest a dropdown selecting the appropriate course

**Comment by esimiele** [comment]
Agreed. I believe the code currently grabs the first plan named _VMAT TBI. No logic included if multiple plans across different courses have that name. Will push a fix in the next few days (if you need a fix faster than that, you can hard code which plan you want optimized by modifying line 428 of MainWindow.xaml.cs).

**Comment by esimiele** [comment]
Resolved. See latest version of beta branch (v2.0 of executable). If multiple _VMAT TBI plans are found, a window will popup requesting you to select the desired course containing the intended VMAT TBI plan for optimization.

**Comment by crcrewso** [comment]
That was fast, thank you
