### ISSUE TITLE
All VMAT

### ISSUE THREAD

**Issue by crcrewso** [esimiele/VMAT-TBI#25]
When selecting All VMAT and changing the energy to something other than the first dropdown entry, the leg fields are not generated with the same energy as the body fields.

**Comment by esimiele** [comment]
I'm guessing the energy is only assigned to 6MV for the leg fields? Should be a simple fix, although I can't imagine why one would want to use an energy higher than 6X for the legs :)

**Comment by crcrewso** [comment]
I can see where you're coming from, unfortunately multi energy optimization is only supported in eclipse optimizers after 16.0.

**Comment by esimiele** [comment]
Haha good point. Totally forgot that was a limitation. Will push a fix soon

**Comment by crcrewso** [comment]
A thought:

Would it make sense for a user to set the number of arcs per energy for each isocenter? I.e. 2 10x and 1 6x for thorax 2 and 2 for pelvis?

**Comment by esimiele** [comment]
Not really, in my experience it is pretty uncommon to utilize multiple energies for a given isocenter. However, now that you pointed this out, that might have been due to a software limitation rather than a real physics limitation.

**Comment by crcrewso** [comment]
The idea came up because one of the datasets we were using to commission our workflow was quite large and the physicist had to add a couple boost fields. The process added quite a bit of time. To me it sits at the boundary between 'this is a one off' and 'could be frequent enough when people get used to it' but as we're barely getting started with this workflow experience is better than theory.

**Comment by esimiele** [comment]
Fixed. See latest push. Although, this raises an interesting question, even for larger patients there really isn't a reason to use an energy greater than 6X for the leg fields. Should the leg isocenters be placed into a separate plan and optimized separately with 6X and the upper and lower plans be summed together? I'm not sure of the best solution since we don't treat TMI/TMLI
