### ISSUE TITLE
Couch structure detection

### ISSUE THREAD

**Issue by crcrewso** [esimiele/VMAT-TBI#26]
Logic for detecting couch needs to be broader to include other clinics' default couch structure names

https://github.com/esimiele/VMAT-TBI/blob/bf03fdc4988bb259738e0817730996a6a1695ae0/VMATTBIAutoPlan/VMATTBI_optLoopMT/optimizationLoop.cs#L230

**Comment by esimiele** [comment]
Should be another simple fix. Maybe allow the user to add couch key words to search for in the structure Id? Will try this route

**Comment by crcrewso** [comment]
That would be amazing. Thank you. 

I'll continue to work on modernizing the config file

**Comment by esimiele** [comment]
Update pushed to master branch. Check it out and let me know if it works/doesn't work
