### ISSUE TITLE
Feature: All VMAT field prep

### ISSUE THREAD

**Issue by crcrewso** [esimiele/VMAT-TBI#30]
Please assign me

When prepping final plans for treatment, the VMAT leg fields should automatically have their collimators rotated and control points adjusted accordingly.

**Comment by esimiele** [comment]
Haha sorry man! I didn't get a chance to implement the code to flip the control points, even though you sent it to me! My bad. Assigned

**Comment by esimiele** [comment]
please see code from https://github.com/Varian-MedicalAffairsAppliedSolutions/MAAS-TXIhelper
as they have solved this exact issue
