### ISSUE TITLE
Dose units error

### ISSUE THREAD

**Issue by wherey4t** [esimiele/VMAT-TBI#34]
After pressing the "Place Beams" button, I get an Eclipse error message that states [There was a problem while executing the script 'VMATTBIautoPlan_v2.1.esapi.dll' Dose units do not match to the system setting.]
I included a screen shot and the Details of the error below.  

Is this because our doses in Eclipse are specified in Gy instead of cGy?  Any idea how to solve this issue?

Many thanks!

![Dose Units error](https://github.com/esimiele/VMAT-TBI/assets/142445312/cfe16b6a-2c69-48be-a01e-daef6fe96b43)
[Dose Units Error.txt](https://github.com/esimiele/VMAT-TBI/files/12362792/Dose.Units.Error.txt)

**Comment by esimiele** [comment]
Your assumption is correct. I wrote this project tailored to our system, where the dose units were in cGy. Unfortunately, there is no clean way to fix it other than searching though the code to change DoseUnit values from cGy to Gy. For the preparation code, see lines 801 & 805 of UI.xaml.cs. Change that to DoseValue.DoseUnit.Gy. There might be other instances throughout the code. Be sure to update all the doses in the configuration file to Gy. Let me know if you run into issues

**Comment by wherey4t** [comment]
Thank you so much for the very quick reply! I went through the code and changed all instances of cGy to Gy and updated the prescription templates, structure constraints, etc.
Will continue testing, but so far so good.
Much appreciated!

**Comment by esimiele** [comment]
Glad to hear it. I'll go ahead and close this issue. Let me know if you run into more problems
