### ISSUE TITLE
Error during Flash Removal

### ISSUE THREAD

**Issue by wherey4t** [esimiele/VMAT-TBI#36]
Hi there,
Sorry to bug you again.  I've got everything working well with the code until the final step of removing the flash and recalculating/renormalizing.  As you can see in the attached screenshot, I get a series of errors for each Beam during this process.  It seems that during this final dose calculation the code is trying to use the GPU, even though the config file is set to "No" for using the GPU for dose calculation and optimization.  
After I close the error window, the code finishes (see attached text file), but when I then open the patient in Eclipse, no dose is calculated.  
Any ideas to solve this are much appreciated!  Thank you.
![Flash removal error](https://github.com/esimiele/VMAT-TBI/assets/142445312/23f288a3-1a27-4b89-9a5e-706b31e99edb)
[Finished_after error.txt](https://github.com/esimiele/VMAT-TBI/files/12420627/Finished_after.error.txt)

**Comment by JasonY-Web** [comment]
I would guess that maybe your code is on network but not on local drive? If so, you may want to move the code to local drive first. I had various issues that were all gone after I moved the code to local drive. Just my 2 cents.

**Comment by esimiele** [comment]
Interesting error. I haven't seen this happen before. My only guess is that the use GPU option is getting turned back on during the process of removing flash. One of the annoying things in ESAPI is that there wasn't/isn't a clear way to clear dose from a plan (required for structure modifications). A way around this is to clear the assigned calculation model to the plan and then re-assign it. This inherently wipes the calculated dose. I'm guessing that during the process of re-assigning the calculation model, it is using the default options for your planning system. That use gpu option in the configuration file is only used in the plug-in/preparation script, not the optimization loop script. Try adding this line on line 574 of progressWindow.xaml.cs (right after p.SetCalculationModel(CalculationType.PhotonVolumeDose, calcModel);):

p.SetCalculationOption(calcModel, "UseGPU", "No");

This should tell Eclipse to set the use gpu option to false when re-assigning the calculation model. Add the above line, recompile, try again. Let me know how it goes.

**Comment by wherey4t** [comment]
Eric, that makes a lot of sense.  I suspect you are correct and that adding that line of code will solve the issue.  I will try that and report back.  Much appreciated!  
JasonY - thank you very much for your suggestion as well.  I am running the code on the local C: drive already though.

**Comment by esimiele** [comment]
Assuming this issue was resolved. Closing
