### ISSUE TITLE
Feature: Increased status information

### ISSUE THREAD

**Issue by crcrewso** [esimiele/VMAT-TBI#5]
Increase information displayed in progress bar, i.e. the current optimization MR and optimization loop number along with the current percent. This is to change the information on the display more often to hopefully let the program look more alive. Combating auto timeout from idle features like Citrix.

**Comment by esimiele** [comment]
It's on the to-do list. I have something working in a console app that does this (essentially just a trace listener listening to the debug output) and it reports the progress to the console UI. I haven't gotten it working for a WPF app. Relatively low on the priority list, but definitely nice to have.

**Comment by esimiele** [comment]
Closing issue. I figured out how to do this with a console application, but not a wpf/windows app. At this point, it's become a time sink to figure this out. Moving on to more pertinent issues.
