### ISSUE TITLE
Dynamic optimization strategy

### ISSUE THREAD

**Issue by Erhushenshou** [esimiele/VMAT-TBI#8]
I wonder what is your dynamic ioptimization strategy. I see the lower objective priority is less than upper objective priority. And in the process I see the hot spot always around 120%.

**Comment by esimiele** [comment]
Please look at VMATTBI_optLoopMT-->optimizationLoop class-->evaluateAndUpdatePlan method. This function contains the logic for adjusting the optimization constraints and priorities
